Bump requests submodule to 2.9.1
Update requests submodule to fix the following error in requests with
Python 3.5:

  TypeError: a bytes-like object is required, not 'str'