Ignore errors when removing temporary folder
On AppVeyor, the following error may occur when removing the temporary
ycmd build folder:

  WindowsError: [Error 145] The directory is not empty

It probably happens because the ycm_core_tests executable is still
locked by some process while removing the folder.